# Generated by Django 3.0.6 on 2020-05-17 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0003_auto_20200515_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='vote',
        ),
        migrations.AddField(
            model_name='link',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
