# Generated by Django 3.0.6 on 2020-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0004_auto_20200517_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
