# Generated by Django 3.0.6 on 2020-05-21 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackers', '0005_auto_20200517_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='نپسندیدن'),
        ),
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندیدن'),
        ),
    ]
